// The bundle is generated by `pnpm build` before Vercel typechecks this entrypoint.
// It is intentionally JavaScript, so it does not ship a declaration file.
// @ts-ignore Generated dist/api.mjs may not have a declaration file in Vercel's checker.
import { createApp } from "../dist/api.mjs";

let appPromise: ReturnType<typeof createApp> | undefined;

export default async function handler(req: any, res: any) {
  appPromise ??= createApp();
  const app = await appPromise;
  return app(req, res);
}
